const vocabData = {
  "全民英檢1000": [
    { zh: "商店", en: "store" },
    { zh: "超級市場", en: "supermarket" },
    { zh: "菜市場", en: "wet market" },
    { zh: "餐廳", en: "restaurant" },
    { zh: "咖啡廳", en: "café" },
    { zh: "書店", en: "bookstore" },
    { zh: "圖書館", en: "library" },
    { zh: "博物館", en: "museum" },
    { zh: "動物園", en: "zoo" },
    { zh: "游樂園", en: "amusement park" },
    { zh: "摩天輪", en: "Ferris wheel" },
    { zh: "電影院", en: "movie theater" },
    { zh: "郵局", en: "post office" },
    { zh: "銀行", en: "bank" },
    { zh: "藥局", en: "pharmacy" },
    { zh: "公園", en: "park" },
    { zh: "海灘", en: "beach" },
    { zh: "運動場", en: "stadium" },
    { zh: "旅館", en: "inn" },
    { zh: "車站", en: "station" },
    { zh: "停車場", en: "parking lot" },
    { zh: "機場", en: "airport" },
    { zh: "地鐵站", en: "subway station" },
    { zh: "公共汽車站", en: "bus stop" },
    { zh: "加油站", en: "gas station" },
    { zh: "醫院", en: "hospital" },
    { zh: "診所", en: "clinic" },
    { zh: "警察局", en: "police station" },
    { zh: "消防局", en: "fire station" },
    { zh: "學校", en: "school" },
    { zh: "大學", en: "university" },
    { zh: "幼稚園", en: "kindergarten" },
    { zh: "高職", en: "vocational school" },
    { zh: "教室", en: "classroom" },
    { zh: "操場", en: "playground" },
    { zh: "實驗室", en: "laboratory" },
    { zh: "校園", en: "campus" },
    { zh: "辦公室", en: "office" },
    { zh: "工廠", en: "factory" },
    { zh: "公司", en: "company" },
    { zh: "商辦大樓", en: "commercial building" },
    { zh: "家", en: "home" },
    { zh: "公寓", en: "apartment" },
    { zh: "摩天大樓", en: "skyscraper" },
    { zh: "旅館", en: "hotel" },
    { zh: "房間", en: "room" },
    { zh: "床", en: "bed" },
    { zh: "沙發", en: "sofa" },
    { zh: "椅子", en: "chair" },
    { zh: "桌子", en: "table" },
    { zh: "櫃子", en: "cabinet" },
    { zh: "冰箱", en: "refrigerator" },
    { zh: "烤箱", en: "oven" },
    { zh: "微波爐", en: "microwave" },
    { zh: "洗衣機", en: "washing machine" },
    { zh: "電腦", en: "computer" },
    { zh: "手機", en: "cellphone" },
    { zh: "電視", en: "television" },
    { zh: "音響", en: "speaker" },
    { zh: "相機", en: "camera" },
    { zh: "手錶", en: "watch" },
    { zh: "衣櫃", en: "wardrobe" },
    { zh: "浴室", en: "bathroom" },
    { zh: "廚房", en: "kitchen" },
    { zh: "餐桌", en: "dining table" },
    { zh: "杯子", en: "cup" },
    { zh: "玻璃杯", en: "glass" },
    { zh: "盤子", en: "plate" },
    { zh: "碗", en: "bowl" },
    { zh: "刀子", en: "knife" },
    { zh: "叉子", en: "fork" },
    { zh: "湯匙", en: "spoon" },
    { zh: "毛巾", en: "towel" },
    { zh: "肥皂", en: "soap" },
    { zh: "牙刷", en: "toothbrush" },
    { zh: "牙膏", en: "toothpaste" },
    { zh: "梳子", en: "comb" },
    { zh: "鏡子", en: "mirror" },
    { zh: "燈", en: "lamp" },
    { zh: "開關", en: "switch" },
    { zh: "窗戶", en: "window" },
    { zh: "門", en: "door" },
    { zh: "鑰匙", en: "key" },
    { zh: "地板", en: "floor" },
    { zh: "牆壁", en: "wall" },
    { zh: "天花板", en: "ceiling" },
    { zh: "屋頂", en: "roof" },
    { zh: "花", en: "flower" },
    { zh: "樹", en: "tree" },
    { zh: "草地", en: "lawn" },
    { zh: "山", en: "mountain" },
    { zh: "河", en: "river" },
    { zh: "瀑布", en: "waterfall" },
    { zh: "湖", en: "lake" },
    { zh: "天空", en: "sky" },
    { zh: "雲", en: "cloud" },
    { zh: "雨", en: "rain" },
    { zh: "雪", en: "snow" },
    { zh: "太陽", en: "sun" },
    { zh: "月亮", en: "moon" },
    { zh: "星星", en: "star" },
    { zh: "風", en: "wind" },
    { zh: "地球", en: "earth" },
    { zh: "火", en: "fire" },
    { zh: "水", en: "water" },
    { zh: "空氣", en: "air" },
    { zh: "土地", en: "land" },
    { zh: "泥土", en: "soil" },

    // 以下開始下一組詞彙
    { zh: "男人", en: "man" },
    { zh: "女人", en: "woman" },
    { zh: "孩子", en: "child" },
    { zh: "父親；爸爸", en: "dad" },
    { zh: "母親；媽媽", en: "mom" },
    { zh: "朋友", en: "friend" },
    { zh: "老師；教員", en: "teacher" },
    { zh: "學生", en: "student" },
    { zh: "醫生", en: "doctor" },
    { zh: "護士", en: "nurse" },
    { zh: "警察", en: "police officer" },
    { zh: "消防員", en: "firefighter" },
    { zh: "工程師", en: "engineer" },
    { zh: "駕駛", en: "driver" },
    { zh: "廚師；大廚", en: "chef" },
    { zh: "演員", en: "actor" },
    { zh: "歌手", en: "singer" },
    { zh: "學生會", en: "student council" },
    { zh: "班級", en: "class" },
    { zh: "課表", en: "schedule" },
    { zh: "功課；作業", en: "homework" },
    { zh: "考试；考試", en: "test" },
    { zh: "分數；成績", en: "grade" },
    { zh: "筆記", en: "notes" },
    { zh: "鉛筆", en: "pencil" },
    { zh: "橡皮擦", en: "eraser" },
    { zh: "尺；尺子", en: "ruler" },
    { zh: "螢光筆", en: "highlighter" },
    { zh: "課本", en: "textbook" },
    { zh: "練習本", en: "workbook" },
    { zh: "螢幕", en: "screen" },
    { zh: "滑鼠", en: "mouse" },
    { zh: "鍵盤", en: "keyboard" },
    { zh: "印表機", en: "printer" },
    { zh: "網路", en: "Internet" },
    { zh: "電子郵件", en: "email" },
    { zh: "字典", en: "dictionary" },
    { zh: "翻譯", en: "translation" },
    { zh: "會議", en: "meeting" },
    { zh: "電話", en: "phone" },
    { zh: "訊息", en: "message" },
    { zh: "電子報", en: "newsletter" },
    { zh: "信箱", en: "mailbox" },
    { zh: "郵件", en: "mail" },
    { zh: "票", en: "ticket" },
    { zh: "護照", en: "passport" },
    { zh: "行李", en: "luggage" },
    { zh: "背包", en: "backpack" },
    { zh: "手提包", en: "handbag" },
    { zh: "購物袋", en: "shopping bag" },
    { zh: "傘", en: "umbrella" },
    { zh: "帽子", en: "hat" },
    { zh: "外套", en: "jacket" },
    { zh: "襯衫", en: "shirt" },
    { zh: "長褲", en: "pants" },
    { zh: "裙子", en: "skirt" },
    { zh: "鞋子", en: "shoes" },
    { zh: "襪子", en: "socks" },
     },
};
