const GRAMMAR_TOWER_QUESTIONS = {
  1: [
    // 第一小關：基礎練習 (50%簡單、20%中等、30%困難)
    { question: "I ___ a student.", options: ["am", "is", "are", "be"], correct: 0, explanation: "I 是第一人稱單數，要用 am", logicHint: "我是第一人稱，想想第一人稱要用什麼 be動詞？" },
    { question: "You ___ my friend.", options: ["am", "is", "are", "be"], correct: 2, explanation: "You 是第二人稱，要用 are", logicHint: "你是第二人稱，想想第二人稱要用什麼 be動詞？" },
    { question: "He ___ a teacher.", options: ["am", "is", "are", "be"], correct: 1, explanation: "He 是第三人稱單數，要用 is", logicHint: "他是第三人稱單數，想想第三人稱單數要用什麼 be動詞？" },
    { question: "She ___ beautiful.", options: ["am", "is", "are", "be"], correct: 1, explanation: "She 是第三人稱單數，要用 is", logicHint: "她是第三人稱單數，想想第三人稱單數要用什麼 be動詞？" },
    { question: "It ___ a cat.", options: ["am", "is", "are", "be"], correct: 1, explanation: "It 是第三人稱單數，要用 is", logicHint: "它是第三人稱單數，想想第三人稱單數要用什麼 be動詞？" },
    { question: "We ___ students.", options: ["am", "is", "are", "be"], correct: 2, explanation: "We 是複數，要用 are", logicHint: "我們是複數，想想複數主詞要用什麼 be動詞？" },
    { question: "They ___ happy.", options: ["am", "is", "are", "be"], correct: 2, explanation: "They 是複數，要用 are", logicHint: "他們是複數，想想複數主詞要用什麼 be動詞？" },
    { question: "My brother ___ tall.", options: ["am", "is", "are", "be"], correct: 1, explanation: "My brother 是單數名詞，要用 is", logicHint: "我的兄弟是單數名詞，想想單數名詞要用什麼 be動詞？" },
    { question: "The dog ___ in the park.", options: ["am", "is", "are", "be"], correct: 1, explanation: "The dog 是單數名詞，要用 is", logicHint: "這隻狗是單數名詞，想想單數名詞要用什麼 be動詞？" },
    { question: "The books ___ on the table.", options: ["am", "is", "are", "be"], correct: 2, explanation: "The books 是複數名詞，要用 are", logicHint: "這些書是複數名詞，想想複數名詞要用什麼 be動詞？" }
  ],
  2: [
    { question: "There ___ one cat.", options: ["is", "are", "am"], correct: 0, explanation: "There is one cat." },
    { question: "There ___ two dogs.", options: ["is", "are", "am"], correct: 1, explanation: "There are two dogs." },
    { question: "I have ___ pencil.", options: ["a", "an", "one"], correct: 0, explanation: "a pencil" },
    { question: "She has ___ apples.", options: ["one", "two", "a"], correct: 1, explanation: "two apples" },
    { question: "There ___ three books on the table.", options: ["is", "are", "am"], correct: 1, explanation: "There are three books." },
    { question: "He has ___ orange.", options: ["a", "an", "one"], correct: 1, explanation: "an orange" },
    { question: "We have ___ pens.", options: ["twelve", "twelves", "twelv"], correct: 0, explanation: "twelve pens" },
    { question: "___ apple is red.", options: ["The", "A", "An"], correct: 2, explanation: "An apple" },
    { question: "There ___ four chairs.", options: ["is", "are", "am"], correct: 1, explanation: "There are four chairs." },
    { question: "He has ___ erasers.", options: ["one", "two", "three"], correct: 2, explanation: "three erasers" }
  ],
  3: [
    { question: "This is ___ book.", options: ["my", "mine", "me"], correct: 0, explanation: "my book" },
    { question: "That is ___ pencil.", options: ["your", "yours", "you"], correct: 0, explanation: "your pencil" },
    { question: "___ name is Tom.", options: ["His", "He", "Him"], correct: 0, explanation: "His name" },
    { question: "This is ___ bag.", options: ["her", "hers", "she"], correct: 0, explanation: "her bag" },
    { question: "___ color is blue.", options: ["Its", "It's", "It"], correct: 0, explanation: "Its color" },
    { question: "This is ___ classroom.", options: ["our", "ours", "we"], correct: 0, explanation: "our classroom" },
    { question: "___ parents are teachers.", options: ["Their", "Theirs", "They"], correct: 0, explanation: "Their parents" },
    { question: "Is this ___ desk?", options: ["your", "yours", "you"], correct: 0, explanation: "your desk" },
    { question: "That is ___ dog.", options: ["his", "him", "he"], correct: 0, explanation: "his dog" },
    { question: "___ house is big.", options: ["Our", "Ours", "We"], correct: 0, explanation: "Our house" }
  ],
  4: [
    { question: "I ___ a teacher.", options: ["am not", "is not", "are not"], correct: 0, explanation: "I am not" },
    { question: "He ___ a student.", options: ["am not", "is not", "are not"], correct: 1, explanation: "He is not" },
    { question: "They ___ at home.", options: ["am not", "is not", "are not"], correct: 2, explanation: "They are not" },
    { question: "She ___ my sister.", options: ["am not", "is not", "are not"], correct: 1, explanation: "She is not" },
    { question: "We ___ ready.", options: ["am not", "is not", "are not"], correct: 2, explanation: "We are not" },
    { question: "You ___ tall.", options: ["am not", "is not", "are not"], correct: 2, explanation: "You are not" },
    { question: "It ___ a dog.", options: ["am not", "is not", "are not"], correct: 1, explanation: "It is not" },
    { question: "My brother ___ at school.", options: ["am not", "is not", "are not"], correct: 1, explanation: "My brother is not" },
    { question: "The cats ___ in the house.", options: ["am not", "is not", "are not"], correct: 2, explanation: "The cats are not" },
    { question: "Anna and I ___ classmates.", options: ["am not", "is not", "are not"], correct: 2, explanation: "Anna and I are not" }
  ],
  5: [
    { question: "___ you a student?", options: ["Are", "Is", "Am"], correct: 0, explanation: "Are you" },
    { question: "___ she your sister?", options: ["Are", "Is", "Am"], correct: 1, explanation: "Is she" },
    { question: "___ they at home?", options: ["Are", "Is", "Am"], correct: 0, explanation: "Are they" },
    { question: "___ he a teacher?", options: ["Are", "Is", "Am"], correct: 1, explanation: "Is he" },
    { question: "___ it a cat?", options: ["Are", "Is", "Am"], correct: 1, explanation: "Is it" },
    { question: "___ I late?", options: ["Are", "Is", "Am"], correct: 2, explanation: "Am I" },
    { question: "___ we ready?", options: ["Are", "Is", "Am"], correct: 0, explanation: "Are we" },
    { question: "___ you my friend?", options: ["Are", "Is", "Am"], correct: 0, explanation: "Are you" },
    { question: "___ this your book?", options: ["Is", "Are", "Am"], correct: 0, explanation: "Is this" },
    { question: "___ those apples?", options: ["Are", "Is", "Am"], correct: 0, explanation: "Are those" }
  ],
  6: [
    { question: "I ___ to school every day.", options: ["go", "goes", "going"], correct: 0, explanation: "I go" },
    { question: "He ___ breakfast at 7.", options: ["eat", "eats", "eating"], correct: 1, explanation: "He eats" },
    { question: "They ___ soccer after class.", options: ["play", "plays", "playing"], correct: 0, explanation: "They play" },
    { question: "She ___ English well.", options: ["speak", "speaks", "speaking"], correct: 1, explanation: "She speaks" },
    { question: "We ___ TV at night.", options: ["watch", "watches", "watching"], correct: 0, explanation: "We watch" },
    { question: "The dog ___ fast.", options: ["run", "runs", "running"], correct: 1, explanation: "The dog runs" },
    { question: "You ___ your homework.", options: ["do", "does", "doing"], correct: 0, explanation: "You do" },
    { question: "My father ___ to work by car.", options: ["go", "goes", "going"], correct: 1, explanation: "My father goes" },
    { question: "The birds ___ in the sky.", options: ["fly", "flies", "flying"], correct: 0, explanation: "The birds fly" },
    { question: "She ___ a book every week.", options: ["read", "reads", "reading"], correct: 1, explanation: "She reads" }
  ],
  7: [
    { question: "I ___ like apples.", options: ["don't", "doesn't", "isn't"], correct: 0, explanation: "I don't like" },
    { question: "He ___ play basketball.", options: ["don't", "doesn't", "isn't"], correct: 1, explanation: "He doesn't play" },
    { question: "They ___ watch TV.", options: ["don't", "doesn't", "isn't"], correct: 0, explanation: "They don't watch" },
    { question: "She ___ eat meat.", options: ["don't", "doesn't", "isn't"], correct: 1, explanation: "She doesn't eat" },
    { question: "We ___ go to school on Sunday.", options: ["don't", "doesn't", "isn't"], correct: 0, explanation: "We don't go" },
    { question: "The dog ___ like water.", options: ["don't", "doesn't", "isn't"], correct: 1, explanation: "The dog doesn't like" },
    { question: "You ___ have a car.", options: ["don't", "doesn't", "isn't"], correct: 0, explanation: "You don't have" },
    { question: "My father ___ cook.", options: ["don't", "doesn't", "isn't"], correct: 1, explanation: "My father doesn't cook" },
    { question: "The birds ___ swim.", options: ["don't", "doesn't", "isn't"], correct: 0, explanation: "The birds don't swim" },
    { question: "She ___ read comics.", options: ["don't", "doesn't", "isn't"], correct: 1, explanation: "She doesn't read" }
  ],
  8: [
    { question: "___ you like apples?", options: ["Do", "Does", "Is"], correct: 0, explanation: "Do you like" },
    { question: "___ he play basketball?", options: ["Do", "Does", "Is"], correct: 1, explanation: "Does he play" },
    { question: "___ they watch TV?", options: ["Do", "Does", "Is"], correct: 0, explanation: "Do they watch" },
    { question: "___ she eat meat?", options: ["Do", "Does", "Is"], correct: 1, explanation: "Does she eat" },
    { question: "___ we go to school on Sunday?", options: ["Do", "Does", "Is"], correct: 0, explanation: "Do we go" },
    { question: "___ the dog like water?", options: ["Do", "Does", "Is"], correct: 1, explanation: "Does the dog like" },
    { question: "___ you have a car?", options: ["Do", "Does", "Is"], correct: 0, explanation: "Do you have" },
    { question: "___ your father cook?", options: ["Do", "Does", "Is"], correct: 1, explanation: "Does your father cook" },
    { question: "___ the birds swim?", options: ["Do", "Does", "Is"], correct: 0, explanation: "Do the birds swim" },
    { question: "___ she read comics?", options: ["Do", "Does", "Is"], correct: 1, explanation: "Does she read" }
  ],
  9: [
    { question: "___ is your name?", options: ["What", "Where", "Who"], correct: 0, explanation: "What is your name?" },
    { question: "___ do you live?", options: ["Where", "What", "Who"], correct: 0, explanation: "Where do you live?" },
    { question: "___ is your birthday?", options: ["When", "What", "Where"], correct: 0, explanation: "When is your birthday?" },
    { question: "___ are you sad?", options: ["Why", "What", "When"], correct: 0, explanation: "Why are you sad?" },
    { question: "___ is your teacher?", options: ["Who", "What", "Where"], correct: 0, explanation: "Who is your teacher?" },
    { question: "___ do you go to school?", options: ["How", "What", "Where"], correct: 0, explanation: "How do you go to school?" },
    { question: "___ is your favorite color?", options: ["What", "Who", "Where"], correct: 0, explanation: "What is your favorite color?" },
    { question: "___ does he play basketball?", options: ["When", "Where", "How"], correct: 2, explanation: "How does he play basketball?" },
    { question: "___ do you get up?", options: ["When", "Where", "How"], correct: 0, explanation: "When do you get up?" },
    { question: "___ is your bag?", options: ["Where", "What", "Who"], correct: 0, explanation: "Where is your bag?" }
  ],
  10: [
    { question: "I ___ at home yesterday.", options: ["was", "were", "am"], correct: 0, explanation: "I was" },
    { question: "He ___ happy last night.", options: ["was", "were", "is"], correct: 0, explanation: "He was" },
    { question: "They ___ in the park.", options: ["was", "were", "are"], correct: 1, explanation: "They were" },
    { question: "She ___ my classmate.", options: ["was", "were", "is"], correct: 0, explanation: "She was" },
    { question: "We ___ ready.", options: ["was", "were", "are"], correct: 1, explanation: "We were" },
    { question: "You ___ late.", options: ["was", "were", "are"], correct: 1, explanation: "You were" },
    { question: "It ___ a sunny day.", options: ["was", "were", "is"], correct: 0, explanation: "It was" },
    { question: "My brother ___ at school.", options: ["was", "were", "is"], correct: 0, explanation: "My brother was" },
    { question: "The cats ___ in the house.", options: ["was", "were", "are"], correct: 1, explanation: "The cats were" },
    { question: "Anna and I ___ classmates.", options: ["was", "were", "are"], correct: 1, explanation: "Anna and I were" }
  ],
  11: [
    { question: "I ___ go to the park tomorrow.", options: ["will", "am", "was"], correct: 0, explanation: "I will go" },
    { question: "She ___ visit her grandma next week.", options: ["will", "is", "was"], correct: 0, explanation: "She will visit" },
    { question: "They ___ play basketball after school.", options: ["will", "are", "were"], correct: 0, explanation: "They will play" },
    { question: "He ___ buy a new bike.", options: ["will", "is", "was"], correct: 0, explanation: "He will buy" },
    { question: "We ___ have a test next Friday.", options: ["will", "are", "were"], correct: 0, explanation: "We will have" },
    { question: "You ___ see the movie tonight.", options: ["will", "are", "were"], correct: 0, explanation: "You will see" },
    { question: "It ___ rain tomorrow.", options: ["will", "is", "was"], correct: 0, explanation: "It will rain" },
    { question: "My father ___ travel to Japan.", options: ["will", "is", "was"], correct: 0, explanation: "My father will travel" },
    { question: "The students ___ join the club.", options: ["will", "are", "were"], correct: 0, explanation: "The students will join" },
    { question: "She ___ cook dinner tonight.", options: ["will", "is", "was"], correct: 0, explanation: "She will cook" }
  ],
  12: [
    { question: "I ___ go to the park tomorrow.", options: ["will not", "am not", "was not"], correct: 0, explanation: "I will not go" },
    { question: "She ___ visit her grandma next week.", options: ["will not", "is not", "was not"], correct: 0, explanation: "She will not visit" },
    { question: "They ___ play basketball after school.", options: ["will not", "are not", "were not"], correct: 0, explanation: "They will not play" },
    { question: "He ___ buy a new bike.", options: ["will not", "is not", "was not"], correct: 0, explanation: "He will not buy" },
    { question: "We ___ have a test next Friday.", options: ["will not", "are not", "were not"], correct: 0, explanation: "We will not have" },
    { question: "You ___ see the movie tonight.", options: ["will not", "are not", "were not"], correct: 0, explanation: "You will not see" },
    { question: "It ___ rain tomorrow.", options: ["will not", "is not", "was not"], correct: 0, explanation: "It will not rain" },
    { question: "My father ___ travel to Japan.", options: ["will not", "is not", "was not"], correct: 0, explanation: "My father will not travel" },
    { question: "The students ___ join the club.", options: ["will not", "are not", "were not"], correct: 0, explanation: "The students will not join" },
    { question: "She ___ cook dinner tonight.", options: ["will not", "is not", "was not"], correct: 0, explanation: "She will not cook" }
  ],
  13: [
    { question: "___ you go to the park tomorrow?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will you go" },
    { question: "___ she visit her grandma next week?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will she visit" },
    { question: "___ they play basketball after school?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will they play" },
    { question: "___ he buy a new bike?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will he buy" },
    { question: "___ we have a test next Friday?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will we have" },
    { question: "___ you see the movie tonight?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will you see" },
    { question: "___ it rain tomorrow?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will it rain" },
    { question: "___ your father travel to Japan?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will your father travel" },
    { question: "___ the students join the club?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will the students join" },
    { question: "___ she cook dinner tonight?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will she cook" }
  ],
  14: [
    { question: "I ___ breakfast now.", options: ["am eating", "eat", "eats"], correct: 0, explanation: "I am eating (現在進行式)" },
    { question: "He ___ TV every day.", options: ["watches", "is watching", "watching"], correct: 0, explanation: "He watches (現在式)" },
    { question: "They ___ soccer at the moment.", options: ["are playing", "play", "plays"], correct: 0, explanation: "They are playing (現在進行式)" },
    { question: "She ___ English on Mondays.", options: ["studies", "is studying", "study"], correct: 0, explanation: "She studies (現在式)" },
    { question: "We ___ in the park now.", options: ["are walking", "walk", "walks"], correct: 0, explanation: "We are walking (現在進行式)" },
    { question: "You ___ to music every morning.", options: ["listen", "are listening", "listens"], correct: 0, explanation: "You listen (現在式)" },
    { question: "It ___ raining.", options: ["is", "are", "was"], correct: 0, explanation: "It is raining (現在進行式)" },
    { question: "My father ___ to work by car.", options: ["goes", "is going", "go"], correct: 0, explanation: "My father goes (現在式)" },
    { question: "The birds ___ in the sky now.", options: ["are flying", "fly", "flies"], correct: 0, explanation: "The birds are flying (現在進行式)" },
    { question: "She ___ a book every week.", options: ["reads", "is reading", "read"], correct: 0, explanation: "She reads (現在式)" }
  ],
  15: [
    { question: "___ you go to school yesterday?", options: ["Did", "Do", "Does"], correct: 0, explanation: "Did you go (過去式問句)" },
    { question: "He ___ breakfast at 7 every day.", options: ["eats", "is eating", "ate"], correct: 0, explanation: "He eats (現在式)" },
    { question: "They ___ in the park now.", options: ["are playing", "play", "played"], correct: 0, explanation: "They are playing (現在進行式)" },
    { question: "She ___ English well last year.", options: ["spoke", "speaks", "is speaking"], correct: 0, explanation: "She spoke (過去式)" },
    { question: "We ___ TV at night.", options: ["watch", "watched", "are watching"], correct: 0, explanation: "We watch (現在式)" },
    { question: "The dog ___ fast yesterday.", options: ["ran", "runs", "is running"], correct: 0, explanation: "The dog ran (過去式)" },
    { question: "You ___ your homework now.", options: ["are doing", "do", "did"], correct: 0, explanation: "You are doing (現在進行式)" },
    { question: "My father ___ to work by car every day.", options: ["goes", "is going", "went"], correct: 0, explanation: "My father goes (現在式)" },
    { question: "The birds ___ in the sky yesterday.", options: ["flew", "fly", "are flying"], correct: 0, explanation: "The birds flew (過去式)" },
    { question: "She ___ a book right now.", options: ["is reading", "reads", "read"], correct: 0, explanation: "She is reading (現在進行式)" }
  ],
  16: [
    { question: "I ___ breakfast now.", options: ["am eating", "eat", "eats"], correct: 0, explanation: "I am eating (現在進行式)" },
    { question: "He ___ TV every day.", options: ["watches", "is watching", "watching"], correct: 0, explanation: "He watches (現在式)" },
    { question: "They ___ soccer at the moment.", options: ["are playing", "play", "plays"], correct: 0, explanation: "They are playing (現在進行式)" },
    { question: "She ___ English on Mondays.", options: ["studies", "is studying", "study"], correct: 0, explanation: "She studies (現在式)" },
    { question: "We ___ in the park now.", options: ["are walking", "walk", "walks"], correct: 0, explanation: "We are walking (現在進行式)" },
    { question: "You ___ to music every morning.", options: ["listen", "are listening", "listens"], correct: 0, explanation: "You listen (現在式)" },
    { question: "It ___ raining.", options: ["is", "are", "was"], correct: 0, explanation: "It is raining (現在進行式)" },
    { question: "My father ___ to work by car.", options: ["goes", "is going", "go"], correct: 0, explanation: "My father goes (現在式)" },
    { question: "The birds ___ in the sky now.", options: ["are flying", "fly", "flies"], correct: 0, explanation: "The birds are flying (現在進行式)" },
    { question: "She ___ a book every week.", options: ["reads", "is reading", "read"], correct: 0, explanation: "She reads (現在式)" }
  ],
  17: [
    { question: "___ you go to the park tomorrow?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will you go" },
    { question: "___ she visit her grandma next week?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will she visit" },
    { question: "___ they play basketball after school?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will they play" },
    { question: "___ he buy a new bike?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will he buy" },
    { question: "___ we have a test next Friday?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will we have" },
    { question: "___ you see the movie tonight?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will you see" },
    { question: "___ it rain tomorrow?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will it rain" },
    { question: "___ your father travel to Japan?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will your father travel" },
    { question: "___ the students join the club?", options: ["Will", "Do", "Did"], correct: 0, explanation: "Will the students join" },
    { question: "___ she cook dinner tonight?", options: ["Will", "Does", "Did"], correct: 0, explanation: "Will she cook" }
  ],
  18: [
    { question: "I ___ at home yesterday.", options: ["was", "were", "am"], correct: 0, explanation: "I was" },
    { question: "He ___ happy last night.", options: ["was", "were", "is"], correct: 0, explanation: "He was" },
    { question: "They ___ in the park.", options: ["was", "were", "are"], correct: 1, explanation: "They were" },
    { question: "She ___ my classmate.", options: ["was", "were", "is"], correct: 0, explanation: "She was" },
    { question: "We ___ ready.", options: ["was", "were", "are"], correct: 1, explanation: "We were" },
    { question: "You ___ late.", options: ["was", "were", "are"], correct: 1, explanation: "You were" },
    { question: "It ___ a sunny day.", options: ["was", "were", "is"], correct: 0, explanation: "It was" },
    { question: "My brother ___ at school.", options: ["was", "were", "is"], correct: 0, explanation: "My brother was" },
    { question: "The cats ___ in the house.", options: ["was", "were", "are"], correct: 1, explanation: "The cats were" },
    { question: "Anna and I ___ classmates.", options: ["was", "were", "are"], correct: 1, explanation: "Anna and I were" }
  ],
  19: [
    { question: "I ___ breakfast now.", options: ["am eating", "eat", "eats"], correct: 0, explanation: "I am eating (現在進行式)" },
    { question: "He ___ TV every day.", options: ["watches", "is watching", "watching"], correct: 0, explanation: "He watches (現在式)" },
    { question: "They ___ soccer at the moment.", options: ["are playing", "play", "plays"], correct: 0, explanation: "They are playing (現在進行式)" },
    { question: "She ___ English on Mondays.", options: ["studies", "is studying", "study"], correct: 0, explanation: "She studies (現在式)" },
    { question: "We ___ in the park now.", options: ["are walking", "walk", "walks"], correct: 0, explanation: "We are walking (現在進行式)" },
    { question: "You ___ to music every morning.", options: ["listen", "are listening", "listens"], correct: 0, explanation: "You listen (現在式)" },
    { question: "It ___ raining.", options: ["is", "are", "was"], correct: 0, explanation: "It is raining (現在進行式)" },
    { question: "My father ___ to work by car.", options: ["goes", "is going", "go"], correct: 0, explanation: "My father goes (現在式)" },
    { question: "The birds ___ in the sky now.", options: ["are flying", "fly", "flies"], correct: 0, explanation: "The birds are flying (現在進行式)" },
    { question: "She ___ a book every week.", options: ["reads", "is reading", "read"], correct: 0, explanation: "She reads (現在式)" }
  ],
  20: [
    { question: "___ you go to school yesterday?", options: ["Did", "Do", "Does"], correct: 0, explanation: "Did you go (過去式問句)" },
    { question: "He ___ breakfast at 7 every day.", options: ["eats", "is eating", "ate"], correct: 0, explanation: "He eats (現在式)" },
    { question: "They ___ in the park now.", options: ["are playing", "play", "played"], correct: 0, explanation: "They are playing (現在進行式)" },
    { question: "She ___ English well last year.", options: ["spoke", "speaks", "is speaking"], correct: 0, explanation: "She spoke (過去式)" },
    { question: "We ___ TV at night.", options: ["watch", "watched", "are watching"], correct: 0, explanation: "We watch (現在式)" },
    { question: "The dog ___ fast yesterday.", options: ["ran", "runs", "is running"], correct: 0, explanation: "The dog ran (過去式)" },
    { question: "You ___ your homework now.", options: ["are doing", "do", "did"], correct: 0, explanation: "You are doing (現在進行式)" },
    { question: "My father ___ to work by car every day.", options: ["goes", "is going", "went"], correct: 0, explanation: "My father goes (現在式)" },
    { question: "The birds ___ in the sky yesterday.", options: ["flew", "fly", "are flying"], correct: 0, explanation: "The birds flew (過去式)" },
    { question: "She ___ a book right now.", options: ["is reading", "reads", "read"], correct: 0, explanation: "She is reading (現在進行式)" }
  ]
}; 