// 文法塔統一題庫系統 - 第十四關：過去式BE動詞問句
// 每個小關卡20題，難度逐關遞增，主詞多樣化

const UNIFIED_QUESTION_BANK = {
  easy: [
    {
      question: "___ you at home yesterday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 you，過去式問句用 Were。",
      logicHint: "主詞是you，be動詞過去式問句用什麼? ",
      difficultWords: ["yesterday", "at home"],
    },
    {
      question: "___ she happy last night?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 she，過去式問句用 Was。",
      logicHint: "主詞是she，be動詞過去式問句用什麼? ",
      difficultWords: ["happy", "last night"],
    },
    {
      question: "___ they in the park yesterday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 they，過去式問句用 Were。",
      logicHint: "主詞是they，be動詞過去式問句用什麼? ",
      difficultWords: ["park", "yesterday"],
    },
    {
      question: "___ we students last year?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 we，過去式問句用 Were。",
      logicHint: "主詞是we，be動詞過去式問句用什麼? ",
      difficultWords: ["students", "last year"],
    },
    {
      question: "___ he my classmate before?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 he，過去式問句用 Was。",
      logicHint: "主詞是he，be動詞過去式問句用什麼? ",
      difficultWords: ["classmate", "before"],
    },
    {
      question: "___ you at the library this morning?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 you，過去式問句用 Were。",
      logicHint: "主詞是you，be動詞過去式問句用什麼? ",
      difficultWords: ["library", "this morning"],
    },
    {
      question: "___ the dog very cute last week?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 the dog，過去式問句用 Was。",
      logicHint: "主詞是the dog，be動詞過去式問句用什麼? ",
      difficultWords: ["dog", "cute", "last week"],
    },
    {
      question: "___ my parents busy yesterday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 my parents，過去式問句用 Were。",
      logicHint: "主詞是my parents，be動詞過去式問句用什麼? ",
      difficultWords: ["parents", "busy", "yesterday"],
    },
    {
      question: "___ Tom and I classmates in junior high?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 Tom and I，過去式問句用 Were。",
      logicHint: "主詞是Tom and I，be動詞過去式問句用什麼? ",
      difficultWords: ["classmates", "junior high"],
    },
    {
      question: "___ the weather cold last month?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 the weather，過去式問句用 Was。",
      logicHint: "主詞是the weather，be動詞過去式問句用什麼? ",
      difficultWords: ["weather", "cold", "last month"],
    },
    {
      question: "___ my sister at the party last Saturday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my sister，過去式問句用 Was。",
      logicHint: "主詞是my sister，be動詞過去式問句用什麼? ",
      difficultWords: ["sister", "party", "last Saturday"],
    },
    {
      question: "___ those boys noisy yesterday afternoon?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 those boys，過去式問句用 Were。",
      logicHint: "主詞是those boys，be動詞過去式問句用什麼? ",
      difficultWords: ["noisy", "yesterday afternoon"],
    },
    {
      question: "___ my grandparents in Japan last year?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 my grandparents，過去式問句用 Were。",
      logicHint: "主詞是my grandparents，be動詞過去式問句用什麼? ",
      difficultWords: ["grandparents", "Japan", "last year"],
    },
    {
      question: "___ the movie interesting?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 the movie，過去式問句用 Was。",
      logicHint: "主詞是the movie，be動詞過去式問句用什麼? ",
      difficultWords: ["movie", "interesting"],
    },
    {
      question: "___ we in the same class two years ago?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 we，過去式問句用 Were。",
      logicHint: "主詞是we，be動詞過去式問句用什麼? ",
      difficultWords: ["same", "class", "two years ago"],
    },
    {
      question: "___ he a good basketball player when he was young?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 he，過去式問句用 Was。",
      logicHint: "主詞是he，be動詞過去式問句用什麼? ",
      difficultWords: ["basketball player", "young"],
    },
    {
      question: "___ you late for school this morning?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 you，過去式問句用 Were。",
      logicHint: "主詞是you，be動詞過去式問句用什麼? ",
      difficultWords: ["late", "school", "this morning"],
    },
    {
      question: "___ the children excited about the trip?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the children，過去式問句用 Were。",
      logicHint: "主詞是the children，be動詞過去式問句用什麼? ",
      difficultWords: ["children", "excited", "trip"],
    },
    {
      question: "___ my father a doctor before retirement?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my father，過去式問句用 Was。",
      logicHint: "主詞是my father，be動詞過去式問句用什麼? ",
      difficultWords: ["father", "doctor", "retirement"],
    },
    {
      question: "___ those apples sweet last season?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 those apples，過去式問句用 Were。",
      logicHint: "主詞是those apples，be動詞過去式問句用什麼? ",
      difficultWords: ["apples", "sweet", "last season"],
    },
    {
      question: "___ the students very quiet during the test?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the students，過去式問句用 Were。",
      logicHint: "主詞是the students，be動詞過去式問句用什麼? ",
      difficultWords: ["students", "quiet", "test"],
    },
    {
      question: "___ my uncle in America in 1990?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my uncle，過去式問句用 Was。",
      logicHint: "主詞是my uncle，be動詞過去式問句用什麼? ",
      difficultWords: ["uncle", "America", "1990"],
    },
    {
      question: "___ the books on the table this morning?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the books，過去式問句用 Were。",
      logicHint: "主詞是the books，be動詞過去式問句用什麼? ",
      difficultWords: ["books", "table", "this morning"],
    },
    {
      question: "___ her answers all correct in the exam?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 her answers，過去式問句用 Were。",
      logicHint: "主詞是her answers，be動詞過去式問句用什麼? ",
      difficultWords: ["answers", "correct", "exam"],
    },
    {
      question: "___ my mother a nurse many years ago?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my mother，過去式問句用 Was。",
      logicHint: "主詞是my mother，be動詞過去式問句用什麼? ",
      difficultWords: ["mother", "nurse", "many years ago"],
    },
    {
      question: "___ the children in the playground after school?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the children，過去式問句用 Were。",
      logicHint: "主詞是the children，be動詞過去式問句用什麼? ",
      difficultWords: ["children", "playground", "after school"],
    },
    {
      question: "___ he very tired last night?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 he，過去式問句用 Was。",
      logicHint: "主詞是he，be動詞過去式問句用什麼? ",
      difficultWords: ["tired", "last night"],
    },
    {
      question: "___ we in the museum last Sunday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 we，過去式問句用 Were。",
      logicHint: "主詞是we，be動詞過去式問句用什麼? ",
      difficultWords: ["museum", "last Sunday"],
    },
    {
      question: "___ the baby asleep all night?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 the baby，過去式問句用 Was。",
      logicHint: "主詞是the baby，be動詞過去式問句用什麼? ",
      difficultWords: ["baby", "asleep", "all night"],
    },
    {
      question: "___ you very helpful yesterday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 you，過去式問句用 Were。",
      logicHint: "主詞是you，be動詞過去式問句用什麼? ",
      difficultWords: ["helpful", "yesterday"],
    },
  ],
  medium: [
    {
      question: "___ my sister at the party last Saturday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my sister，過去式問句用 Was。",
      logicHint: "主詞是my sister，be動詞過去式問句用什麼? ",
      difficultWords: ["sister", "party", "last Saturday"],
    },
    {
      question: "___ those boys noisy yesterday afternoon?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 those boys，過去式問句用 Were。",
      logicHint: "主詞是those boys，be動詞過去式問句用什麼? ",
      difficultWords: ["noisy", "yesterday afternoon"],
    },
    {
      question: "___ my grandparents in Japan last year?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 my grandparents，過去式問句用 Were。",
      logicHint: "主詞是my grandparents，be動詞過去式問句用什麼? ",
      difficultWords: ["grandparents", "Japan", "last year"],
    },
    {
      question: "___ the movie interesting?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 the movie，過去式問句用 Was。",
      logicHint: "主詞是the movie，be動詞過去式問句用什麼? ",
      difficultWords: ["movie", "interesting"],
    },
    {
      question: "___ we in the same class two years ago?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 we，過去式問句用 Were。",
      logicHint: "主詞是we，be動詞過去式問句用什麼? ",
      difficultWords: ["same", "class", "two years ago"],
    },
    {
      question: "___ he a good basketball player when he was young?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 he，過去式問句用 Was。",
      logicHint: "主詞是he，be動詞過去式問句用什麼? ",
      difficultWords: ["basketball player", "young"],
    },
    {
      question: "___ you late for school this morning?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 you，過去式問句用 Were。",
      logicHint: "主詞是you，be動詞過去式問句用什麼? ",
      difficultWords: ["late", "school", "this morning"],
    },
    {
      question: "___ the children excited about the trip?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the children，過去式問句用 Were。",
      logicHint: "主詞是the children，be動詞過去式問句用什麼? ",
      difficultWords: ["children", "excited", "trip"],
    },
    {
      question: "___ my father a doctor before retirement?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my father，過去式問句用 Was。",
      logicHint: "主詞是my father，be動詞過去式問句用什麼? ",
      difficultWords: ["father", "doctor", "retirement"],
    },
    {
      question: "___ those apples sweet last season?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 those apples，過去式問句用 Were。",
      logicHint: "主詞是those apples，be動詞過去式問句用什麼? ",
      difficultWords: ["apples", "sweet", "last season"],
    },
    {
      question: "___ the students very quiet during the test?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the students，過去式問句用 Were。",
      logicHint: "主詞是the students，be動詞過去式問句用什麼? ",
      difficultWords: ["students", "quiet", "test"],
    },
    {
      question: "___ my uncle in America in 1990?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my uncle，過去式問句用 Was。",
      logicHint: "主詞是my uncle，be動詞過去式問句用什麼? ",
      difficultWords: ["uncle", "America", "1990"],
    },
    {
      question: "___ the books on the table this morning?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the books，過去式問句用 Were。",
      logicHint: "主詞是the books，be動詞過去式問句用什麼? ",
      difficultWords: ["books", "table", "this morning"],
    },
    {
      question: "___ her answers all correct in the exam?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 her answers，過去式問句用 Were。",
      logicHint: "主詞是her answers，be動詞過去式問句用什麼? ",
      difficultWords: ["answers", "correct", "exam"],
    },
    {
      question: "___ my mother a nurse many years ago?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my mother，過去式問句用 Was。",
      logicHint: "主詞是my mother，be動詞過去式問句用什麼? ",
      difficultWords: ["mother", "nurse", "many years ago"],
    },
    {
      question: "___ the children in the playground after school?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the children，過去式問句用 Were。",
      logicHint: "主詞是the children，be動詞過去式問句用什麼? ",
      difficultWords: ["children", "playground", "after school"],
    },
    {
      question: "___ he very tired last night?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 he，過去式問句用 Was。",
      logicHint: "主詞是he，be動詞過去式問句用什麼? ",
      difficultWords: ["tired", "last night"],
    },
    {
      question: "___ we in the museum last Sunday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 we，過去式問句用 Were。",
      logicHint: "主詞是we，be動詞過去式問句用什麼? ",
      difficultWords: ["museum", "last Sunday"],
    },
    {
      question: "___ the baby asleep all night?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 the baby，過去式問句用 Was。",
      logicHint: "主詞是the baby，be動詞過去式問句用什麼? ",
      difficultWords: ["baby", "asleep", "all night"],
    },
    {
      question: "___ you very helpful yesterday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 you，過去式問句用 Were。",
      logicHint: "主詞是you，be動詞過去式問句用什麼? ",
      difficultWords: ["helpful", "yesterday"],
    },
  ],
  hard: [
    {
      question: "___ the students very quiet during the test?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the students，過去式問句用 Were。",
      logicHint: "主詞是the students，be動詞過去式問句用什麼? ",
      difficultWords: ["students", "quiet", "test"],
    },
    {
      question: "___ my uncle in America in 1990?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my uncle，過去式問句用 Was。",
      logicHint: "主詞是my uncle，be動詞過去式問句用什麼? ",
      difficultWords: ["uncle", "America", "1990"],
    },
    {
      question: "___ the books on the table this morning?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the books，過去式問句用 Were。",
      logicHint: "主詞是the books，be動詞過去式問句用什麼? ",
      difficultWords: ["books", "table", "this morning"],
    },
    {
      question: "___ her answers all correct in the exam?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 her answers，過去式問句用 Were。",
      logicHint: "主詞是her answers，be動詞過去式問句用什麼? ",
      difficultWords: ["answers", "correct", "exam"],
    },
    {
      question: "___ my mother a nurse many years ago?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 my mother，過去式問句用 Was。",
      logicHint: "主詞是my mother，be動詞過去式問句用什麼? ",
      difficultWords: ["mother", "nurse", "many years ago"],
    },
    {
      question: "___ the children in the playground after school?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 the children，過去式問句用 Were。",
      logicHint: "主詞是the children，be動詞過去式問句用什麼? ",
      difficultWords: ["children", "playground", "after school"],
    },
    {
      question: "___ he very tired last night?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 he，過去式問句用 Was。",
      logicHint: "主詞是he，be動詞過去式問句用什麼? ",
      difficultWords: ["tired", "last night"],
    },
    {
      question: "___ we in the museum last Sunday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 we，過去式問句用 Were。",
      logicHint: "主詞是we，be動詞過去式問句用什麼? ",
      difficultWords: ["museum", "last Sunday"],
    },
    {
      question: "___ the baby asleep all night?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 0,
      explanation: "主詞 the baby，過去式問句用 Was。",
      logicHint: "主詞是the baby，be動詞過去式問句用什麼? ",
      difficultWords: ["baby", "asleep", "all night"],
    },
    {
      question: "___ you very helpful yesterday?",
      options: ["Was", "Were", "Is", "Are"],
      correct: 1,
      explanation: "主詞 you，過去式問句用 Were。",
      logicHint: "主詞是you，be動詞過去式問句用什麼? ",
      difficultWords: ["helpful", "yesterday"],
    },
  ]
};

const DIFFICULT_WORDS_TRANSLATION = {
  "yesterday": "昨天",
  "at home": "在家",
  "happy": "開心的",
  "last night": "昨晚",
  "park": "公園",
  "students": "學生們",
  "last year": "去年",
  "classmate": "同學",
  "before": "以前、之前",
  "library": "圖書館",
  "this morning": "今天早上",
  "dog": "狗",
  "cute": "可愛的",
  "last week": "上週",
  "parents": "父母",
  "busy": "忙碌的",
  "junior high": "國中",
  "weather": "天氣",
  "cold": "寒冷的",
  "last month": "上個月",
  "sister": "姊妹",
  "party": "派對",
  "last Saturday": "上週六",
  "noisy": "吵鬧的",
  "yesterday afternoon": "昨天下午",
  "grandparents": "祖父母",
  "Japan": "日本",
  "movie": "電影",
  "interesting": "有趣的",
  "same": "相同的",
  "class": "班級",
  "two years ago": "兩年前",
  "basketball player": "籃球員",
  "young": "年輕的",
  "late": "遲到的",
  "school": "學校",
  "children": "孩子們",
  "excited": "興奮的",
  "trip": "旅行",
  "father": "父親",
  "doctor": "醫生",
  "retirement": "退休",
  "apples": "蘋果們",
  "sweet": "甜的",
  "last season": "上季",
  "quiet": "安靜的",
  "test": "考試",
  "uncle": "叔叔、伯伯",
  "America": "美國",
  "1990": "1990年",
  "books": "書（複數）",
  "table": "桌子",
  "answers": "答案們",
  "correct": "正確的",
  "exam": "考試",
  "mother": "母親",
  "nurse": "護士",
  "many years ago": "許多年前",
  "playground": "操場",
  "after school": "放學後",
  "tired": "疲倦的",
  "museum": "博物館",
  "last Sunday": "上週日",
  "baby": "嬰兒",
  "asleep": "睡著的",
  "all night": "整晚",
  "helpful": "有幫助的"
};

function getRandomQuestions(subLevel, count = 10) {
  // 取得難度對應
  let difficulty = subLevel;
  if (LEVEL_CONFIG && LEVEL_CONFIG[subLevel]) {
    difficulty = LEVEL_CONFIG[subLevel].difficulty;
  }
  const questions = UNIFIED_QUESTION_BANK[difficulty];
  if (!questions) {
    console.error(`找不到難度 ${subLevel} 的題目`);
    return [];
  }
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

function getLevelInfo(subLevel) {
  return {
    title: `第十四關：過去式BE動詞問句 - ${subLevel === 'easy' ? '簡單' : subLevel === 'medium' ? '中級' : '困難'}關卡`,
    description: `學習過去式be動詞問句的用法，${subLevel === 'easy' ? '基礎題目' : subLevel === 'medium' ? '進階題目' : '高級題目'}`
  };
}

// 關卡配置
const LEVEL_CONFIG = {
    sub1: {
        name: "星辰之塔第一層",
        description: "探索be動詞過去式問句的基礎",
        difficulty: "easy"
    },
    sub2: {
        name: "星辰之塔第二層", 
        description: "挑戰更複雜的問句型",
        difficulty: "medium"
    },
    sub3: {
        name: "星辰之塔頂層",
        description: "征服最困難的問句挑戰",
        difficulty: "hard"
    }
};

// 困難單字詞典
const DIFFICULT_WORDS = DIFFICULT_WORDS_TRANSLATION;

function getAllLevels() {
  return ['easy', 'medium', 'hard'];
} 