window.myQuizCore = [
  { sentence: "My ___ cooks dinner on weekends.", answer: "husband", zh: "我的丈夫週末做晚餐。" },
  { sentence: "His ___ teaches at the elementary school.", answer: "wife", zh: "他的妻子在小學教書。" },
  { sentence: "The ___ cleans the house every morning.", answer: "housewife", zh: "那位家庭主婦每天早上打掃房子。" },
  { sentence: "Miss Lin is our new ___ teacher.", answer: "English", zh: "林小姐是我們的新英語老師。" },
  { sentence: "She is ___ years old this year.", answer: "thirteen", zh: "她今年十三歲。" },
  { sentence: "He scored ___ points in the game.", answer: "fourteen", zh: "他在比賽中得到了十四分。" },
  { sentence: "There are ___ students in my class.", answer: "fifteen", zh: "我的班上有十五位學生。" },
  { sentence: "___ birds sat on the fence.", answer: "sixteen", zh: "有十六隻鳥坐在圍欄上。" },
  { sentence: "They baked ___ cookies for the party.", answer: "seventeen", zh: "他們為派對烤了十七塊餅乾。" },
  { sentence: "My sister turned ___ last month.", answer: "eighteen", zh: "我妹妹上個月滿十八歲。" },
  { sentence: "___ fish swam in the pond.", answer: "nineteen", zh: "池塘裡有十九條魚游泳。" },
  { sentence: "___ students walked to school together.", answer: "twenty", zh: "二十名學生一起走去學校。" },
  { sentence: "The street is ___ meters long.", answer: "thirty", zh: "那條街有三十公尺長。" },
  { sentence: "He picked ___ apples from the tree.", answer: "forty", zh: "他從樹上摘了四十顆蘋果。" },
  { sentence: "She saved ___ dollars for the trip.", answer: "fifty", zh: "她為這趟旅行存了五十元。" },
  { sentence: "It takes ___ minutes to finish this task.", answer: "sixty", zh: "完成這項任務需要六十分鐘。" },
  { sentence: "___ people attended the meeting.", answer: "seventy", zh: "有七十個人參加了會議。" },
  { sentence: "The road is ___ kilometers long.", answer: "eighty", zh: "這條路有八十公里長。" },
  { sentence: "She read ___ pages of the book.", answer: "ninety", zh: "她讀了這本書的九十頁。" },
  { sentence: "They sold a ___ tickets for the concert.", answer: "thousand", zh: "他們為音樂會賣出了一千張票。" },
  { sentence: "Please write your phone ___ here.", answer: "number", zh: "請在這裡寫下你的電話號碼。" },
  { sentence: "Open your ___ to page ten.", answer: "workbook", zh: "請打開你的作業本到第十頁。" },
  { sentence: "Use a ___ to clean the whiteboard.", answer: "brush", zh: "用刷子清潔白板。" },
  { sentence: "Her ___ rang during class.", answer: "cellphone", zh: "她的手機在上課時響了。" },
  { sentence: "He rides his ___ to the park.", answer: "scooter", zh: "他騎踏板車去公園。" },
  { sentence: "They have a birthday ___ on Saturday.", answer: "party", zh: "他們星期六有一場生日派對。" },
  { sentence: "She wrapped the ___ for her friend.", answer: "gift", zh: "她把禮物包好送給朋友。" },
  { sentence: "We eat lunch at ___ every day.", answer: "noon", zh: "我們每天中午吃午餐。" },
  { sentence: "Be careful not to ___ the glass.", answer: "break", zh: "小心別把玻璃杯打破。" },
  { sentence: "That flower is very ___ .", answer: "pretty", zh: "那朵花非常漂亮。" },
  { sentence: "She is ___ to solve the problem quickly.", answer: "able", zh: "她能很快地解決這個問題。" },
  { sentence: "The ___ boy plays soccer every day.", answer: "young", zh: "那個年輕男孩每天踢足球。" },
  { sentence: "I am ___ after eating dinner.", answer: "full", zh: "吃完晚餐後我很飽。" },
  { sentence: "You are ___ to find a seat.", answer: "lucky", zh: "你很幸運找到一個座位。" },
  { sentence: "I was ___ tired after running.", answer: "so", zh: "跑完後我如此疲倦。" },
  { sentence: "She is ___ excited about the trip.", answer: "really", zh: "她對這次旅行真地很興奮。" },
  { sentence: "___ the test, be quiet.", answer: "During", zh: "在考試期間要保持安靜。" },
  { sentence: "There is a park ___ my house.", answer: "near", zh: "我家附近有一個公園。" },
  { sentence: "I ___ the answer is correct.", answer: "guess", zh: "我猜想答案是對的。" },
  { sentence: "We eat dinner in the ___ .", answer: "dining room", zh: "我們在飯廳吃晚餐。" }
];
