// 為題目添加專屬判斷提示的腳本
const logicHints = {
    // 第一小關 - 基礎主詞搭配
    "I ___ a student.": "我是第一人稱，想想第一人稱要用什麼 be動詞？",
    "You ___ my friend.": "你是第二人稱，想想第二人稱要用什麼 be動詞？",
    "He ___ a teacher.": "他是第三人稱單數，想想第三人稱單數要用什麼 be動詞？",
    "She ___ beautiful.": "她是第三人稱單數，想想第三人稱單數要用什麼 be動詞？",
    "It ___ a cat.": "它是第三人稱單數，想想第三人稱單數要用什麼 be動詞？",
    "We ___ students.": "我們是複數，想想複數主詞要用什麼 be動詞？",
    "They ___ happy.": "他們是複數，想想複數主詞要用什麼 be動詞？",
    "My brother ___ tall.": "我的兄弟是單數名詞，想想單數名詞要用什麼 be動詞？",
    "The dog ___ in the park.": "這隻狗是單數名詞，想想單數名詞要用什麼 be動詞？",
    "The books ___ on the table.": "這些書是複數名詞，想想複數名詞要用什麼 be動詞？",
    "My parents ___ at home.": "我的父母是複數名詞，想想複數名詞要用什麼 be動詞？",
    "The weather ___ nice.": "天氣是單數概念，想想單數要用什麼 be動詞？",
    "The flowers ___ red.": "這些花是複數，想想複數要用什麼 be動詞？",
    "Tom and Jerry ___ friends.": "湯姆和傑瑞是兩個人，想想複數主詞要用什麼 be動詞？",
    "The sky ___ blue.": "天空是單數概念，想想單數要用什麼 be動詞？",
    "The cars ___ white.": "這些車是複數，想想複數要用什麼 be動詞？",
    "Anna and I ___ classmates.": "安娜和我是兩個人，想想複數主詞要用什麼 be動詞？",
    "My best friend ___ a doctor.": "我最好的朋友是一個人，想想單數主詞要用什麼 be動詞？",
    "Mathematics ___ my favorite subject.": "數學是一門學科，想想單數學科要用什麼 be動詞？",
    "The police ___ investigating the case.": "警察是集合名詞，通常視為複數，想想複數要用什麼 be動詞？",
    
    // 第二小關 - 職業與身份
    "I ___ a doctor.": "我是第一人稱，想想第一人稱要用什麼 be動詞？",
    "She ___ a nurse.": "她是第三人稱單數，想想第三人稱單數要用什麼 be動詞？",
    "He ___ an engineer.": "他是第三人稱單數，想想第三人稱單數要用什麼 be動詞？",
    "We ___ students.": "我們是複數，想想複數主詞要用什麼 be動詞？",
    "They ___ teachers.": "他們是複數，想想複數主詞要用什麼 be動詞？",
    "You ___ a good student.": "你是第二人稱，想想第二人稱要用什麼 be動詞？",
    "My father ___ a driver.": "我的父親是一個人，想想單數主詞要用什麼 be動詞？",
    "My mother ___ a cook.": "我的母親是一個人，想想單數主詞要用什麼 be動詞？",
    "My sisters ___ doctors.": "我的姐妹們是複數，想想複數主詞要用什麼 be動詞？",
    "The new teacher ___ very kind.": "新老師是一個人，想想單數主詞要用什麼 be動詞？",
    "All the students ___ excited.": "所有學生是複數，想想複數主詞要用什麼 be動詞？",
    "Each student ___ responsible.": "每個學生是單數，想想單數主詞要用什麼 be動詞？",
    "Both of us ___ ready to go.": "我們兩個是複數，想想複數主詞要用什麼 be動詞？",
    "The staff ___ working hard.": "員工是集合名詞，通常視為複數，想想複數要用什麼 be動詞？",
    "The committee ___ meeting tomorrow.": "委員會是集合名詞，通常視為單數，想想單數要用什麼 be動詞？",
    "The team ___ practicing now.": "團隊是集合名詞，通常視為單數，想想單數要用什麼 be動詞？",
    "The family ___ going on vacation.": "家庭是集合名詞，通常視為單數，想想單數要用什麼 be動詞？",
    "The audience ___ clapping loudly.": "觀眾是集合名詞，通常視為複數，想想複數要用什麼 be動詞？",
    "The crowd ___ cheering for the team.": "人群是集合名詞，通常視為複數，想想複數要用什麼 be動詞？",
    "Politics ___ complicated.": "政治是單數概念，想想單數要用什麼 be動詞？",
    
    // 第三小關 - 地點與狀態
    "I ___ at school.": "我是第一人稱，想想第一人稱要用什麼 be動詞？",
    "You ___ here.": "你是第二人稱，想想第二人稱要用什麼 be動詞？",
    "He ___ in the library.": "他是第三人稱單數，想想第三人稱單數要用什麼 be動詞？",
    "They ___ at the store.": "他們是複數，想想複數主詞要用什麼 be動詞？",
    "The cat ___ on the chair.": "這隻貓是單數，想想單數要用什麼 be動詞？",
    "The birds ___ in the sky.": "這些鳥是複數，想想複數要用什麼 be動詞？",
    "The children ___ in the park.": "這些孩子是複數，想想複數要用什麼 be動詞？",
    "My friends ___ at the party.": "我的朋友們是複數，想想複數要用什麼 be動詞？",
    "The dog ___ under the table.": "這隻狗是單數，想想單數要用什麼 be動詞？",
    "The books ___ in the bag.": "這些書是複數，想想複數要用什麼 be動詞？",
    "The sun ___ bright today.": "太陽是單數，想想單數要用什麼 be動詞？",
    "The stars ___ visible tonight.": "這些星星是複數，想想複數要用什麼 be動詞？",
    "The moon ___ full.": "月亮是單數，想想單數要用什麼 be動詞？",
    "The clouds ___ white.": "這些雲是複數，想想複數要用什麼 be動詞？",
    "The river ___ deep.": "這條河是單數，想想單數要用什麼 be動詞？",
    "The mountains ___ high.": "這些山是複數，想想複數要用什麼 be動詞？",
    "The ocean ___ blue.": "海洋是單數，想想單數要用什麼 be動詞？",
    "The trees ___ green.": "這些樹是複數，想想複數要用什麼 be動詞？",
    "The grass ___ wet.": "草是單數概念，想想單數要用什麼 be動詞？",
    "The leaves ___ falling.": "這些葉子是複數，想想複數要用什麼 be動詞？",
    
    // 第二關 - There is/are
    "There ___ a book on the table.": "There is/are 結構，後面是單數名詞，想想要用什麼？",
    "There ___ three cats in the garden.": "There is/are 結構，後面是複數名詞，想想要用什麼？",
    "There ___ one apple in the basket.": "There is/are 結構，後面是單數名詞，想想要用什麼？",
    "There ___ two dogs.": "There is/are 結構，後面是複數名詞，想想要用什麼？",
    "There ___ three books.": "There is/are 結構，後面是複數名詞，想想要用什麼？",
    "There ___ a pen on the desk.": "There is/are 結構，後面是單數名詞，想想要用什麼？",
    "There ___ many students.": "There is/are 結構，many 後面是複數，想想要用什麼？",
    "There ___ some water.": "There is/are 結構，water 是不可數名詞，想想要用什麼？",
    "There ___ a lot of people.": "There is/are 結構，people 是複數，想想要用什麼？",
    "There ___ five apples.": "There is/are 結構，後面是複數名詞，想想要用什麼？",
    "There ___ several cars.": "There is/are 結構，several 後面是複數，想想要用什麼？",
    "There ___ no milk.": "There is/are 結構，milk 是不可數名詞，想想要用什麼？",
    "There ___ a cat under the table.": "There is/are 結構，後面是單數名詞，想想要用什麼？",
    "There ___ many flowers in the garden.": "There is/are 結構，many 後面是複數，想想要用什麼？",
    "There ___ no time left.": "There is/are 結構，time 是不可數名詞，想想要用什麼？",
    "There ___ a lot of traffic today.": "There is/are 結構，traffic 是不可數名詞，想想要用什麼？",
    "There ___ plenty of food.": "There is/are 結構，food 是不可數名詞，想想要用什麼？",
    "There ___ many problems to solve.": "There is/are 結構，many 後面是複數，想想要用什麼？",
    "There ___ a great deal of work.": "There is/are 結構，work 是不可數名詞，想想要用什麼？",
    "There ___ several options available.": "There is/are 結構，several 後面是複數，想想要用什麼？",
    
    // 第二關 - 形容詞搭配
    "The weather ___ cold today.": "天氣是單數概念，想想單數要用什麼 be動詞？",
    "The flowers ___ beautiful.": "這些花是複數，想想複數要用什麼 be動詞？",
    "My sister ___ very smart.": "我的姐妹是一個人，想想單數要用什麼 be動詞？",
    "The movie ___ interesting.": "這部電影是單數，想想單數要用什麼 be動詞？",
    "The sky ___ blue.": "天空是單數概念，想想單數要用什麼 be動詞？",
    "The cars ___ white.": "這些車是複數，想想複數要用什麼 be動詞？",
    "The children ___ excited.": "這些孩子是複數，想想複數要用什麼 be動詞？",
    "My shirt ___ yellow.": "我的襯衫是單數，想想單數要用什麼 be動詞？",
    "Her shoes ___ black.": "她的鞋子是複數，想想複數要用什麼 be動詞？",
    "The apple ___ red.": "這個蘋果是單數，想想單數要用什麼 be動詞？",
    "The bananas ___ yellow.": "這些香蕉是複數，想想複數要用什麼 be動詞？",
    "The rose ___ pink.": "這朵玫瑰是單數，想想單數要用什麼 be動詞？",
    "The leaves ___ green.": "這些葉子是複數，想想複數要用什麼 be動詞？",
    "The grass ___ green.": "草是單數概念，想想單數要用什麼 be動詞？",
    "The beautiful flowers in the garden ___ blooming.": "這些美麗的花是複數，想想複數要用什麼 be動詞？",
    "My favorite book on the shelf ___ interesting.": "我最喜歡的書是單數，想想單數要用什麼 be動詞？",
    "The new teacher in our class ___ very kind.": "新老師是一個人，想想單數要用什麼 be動詞？",
    "All the people at the party ___ having fun.": "所有的人是複數，想想複數要用什麼 be動詞？",
    "Each student ___ responsible.": "每個學生是單數，想想單數要用什麼 be動詞？",
    "Both of us ___ ready to go.": "我們兩個是複數，想想複數要用什麼 be動詞？",
    
    // 第二關 - 時間表達
    "It ___ 3 o'clock.": "It 是單數，想想單數要用什麼 be動詞？",
    "Today ___ Monday.": "今天是一個時間概念，想想單數要用什麼 be動詞？",
    "The classes ___ over.": "這些課程是複數，想想複數要用什麼 be動詞？",
    "The days ___ long in summer.": "這些日子是複數，想想複數要用什麼 be動詞？",
    "Spring ___ my favorite season.": "春天是單數，想想單數要用什麼 be動詞？",
    "The holidays ___ coming soon.": "這些假期是複數，想想複數要用什麼 be動詞？",
    "It ___ sunny today.": "It 是單數，想想單數要用什麼 be動詞？",
    "The nights ___ short in winter.": "這些夜晚是複數，想想複數要用什麼 be動詞？",
    "It ___ cold today.": "It 是單數，想想單數要用什麼 be動詞？",
    "It ___ raining.": "It 是單數，想想單數要用什麼 be動詞？",
    "The hours ___ long.": "這些小時是複數，想想複數要用什麼 be動詞？",
    "The minutes ___ short.": "這些分鐘是複數，想想複數要用什麼 be動詞？",
    "Mathematics ___ my favorite subject.": "數學是一門學科，想想單數學科要用什麼 be動詞？",
    "The news ___ very important.": "新聞是單數概念，想想單數要用什麼 be動詞？",
    "Politics ___ complicated.": "政治是單數概念，想想單數要用什麼 be動詞？",
    "The team ___ practicing now.": "團隊是集合名詞，通常視為單數，想想單數要用什麼 be動詞？",
    "The committee ___ meeting tomorrow.": "委員會是集合名詞，通常視為單數，想想單數要用什麼 be動詞？",
    "The family ___ going on vacation.": "家庭是集合名詞，通常視為單數，想想單數要用什麼 be動詞？",
    "Bread and butter ___ my breakfast.": "麵包和奶油是一個整體，想想單數要用什麼 be動詞？",
    "Fish and chips ___ my favorite food.": "魚和薯條是一個整體，想想單數要用什麼 be動詞？"
};

console.log('邏輯提示已準備完成，共', Object.keys(logicHints).length, '個提示'); 